#ifndef _GPIO_GPIO_H
#define _GPIO_GPIO_H

#include "util.h"

#define GPIO_PERIF_REG_MAP_BASE (PERIF_ADDRESS + 0x200000)

#define GPIO_GPFSEL0_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x0))
#define GPIO_GPFSEL1_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x4))
#define GPIO_GPFSEL2_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x8))
#define GPIO_GPFSEL3_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0xC))
#define GPIO_GPFSEL4_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x10))
#define GPIO_GPFSEL5_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x14))
#define GPIO_FSEL_SIZE 3
#define GPIO_FSEL14_BIT 12 /* GPIO 14 PIN */
#define GPIO_FSEL15_BIT 15 /* GPIO 15 PIN */

#define GPIO_GPSET0_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x1C))
#define GPIO_GPSET1_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x20))

#define GPIO_GPCLR0_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x28))

#define GPIO_GPLEV0_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x34))
#define GPIO_GPLEV1_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x38))

#define GPIO_GPEDS0_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x40))
#define GPIO_GPEDS1_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x44))

#define GPIO_GPHEN0_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x64))
#define GPIO_GPHEN1_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x68))

#define GPIO_GPPUD_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x94))
#define GPIO_GPPUDCLK0_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x98))
#define GPIO_GPPUDCLK1_REG ((reg32 *)(GPIO_PERIF_REG_MAP_BASE + 0x9C))
#define GPIO_GPPUD_Off 0b00
#define GPIO_GPPUD_Enable_Pull_Down 0b01
#define GPIO_GPPUD_Enable_Pull_Up 0b10
#define GPIO_GPPUDCLK_NO_EFFECT 0

#endif /* _GPIO_GPIO_H */